name: Build

on: [push, pull_request]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install
      - run: npm run test
  build:
    name: Build
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Get timestamp
        id: timestamp
        run: echo "::set-output name=timestamp::$(date +'%Y%m%d%H%M%S')"
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install
      - run: npm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@main
        with:
          name: portfolioBalancer_${{ steps.timestamp.outputs.timestamp }}
          path: public
